### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Squall-Leonhart** [TamanegiMage/ACT_EnmityPlugin#15]
Load Image error reported in ACT when starting.

10/01/2019 9:48:28 AM: Error: LoadAddons: Y:\Program Files\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ACT\OverlayPlugin\addons\EnmityOverlay.dll: System.IO.FileLoadException: Could not load file or assembly 'file:///Y:\Program Files\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ACT\OverlayPlugin\addons\EnmityOverlay.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///Y:\Program Files\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ACT\OverlayPlugin\addons\EnmityOverlay.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons() in f:\Repositories\OverlayPlugin-Compiler\OverlayPlugin\OverlayPlugin.Core\PluginMain.cs:line 231

**Comment by Squall-Leonhart** [comment]
Don't mind me,  Once i saw the full error i realised it was the windows download blocking.
